spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    #最大活跃数
    #    maxActive: 20
    #    #初始化数量
    #    initialSize: 1
    #    #最大连接等待超时时间
    #    maxWait: 60000
    #    #打开PSCache，并且指定每个连接PSCache的大小
    #    poolPreparedStatements: true
    #    maxPoolPreparedStatementPerConnectionSize: 20
    #    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #    minIdle: 1
    #    timeBetweenEvictionRunsMillis: 60000
    #    minEvictableIdleTimeMillis: 300000
    #    validationQuery: select 1 from dual
    #    testWhileIdle: true
    #    testOnBorrow: false
    #    testOnReturn: false
    #    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    #    filters: stat, wall, log4j
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
      username: root
      password: root
      #最大活跃数
      max-active: 20
      #初始化数量
      initial-size: 1
      #最大连接等待超时时间
      max-wait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j
